version: '3'

vars:
  GIT_TAG:
    sh: git describe --tags --abbrev=0

tasks:
  start:
    cmds:
      - go run -ldflags="-X 'main.release={{.GIT_TAG}}'" ../cmd/server/*.go
    silent: false
  dbuild:
    cmds:
      - docker build -t go-webapp-golangdk:{{.GIT_TAG}} ../
    silent: false
  dstart:
    cmds:
      - docker run -d -p 8080:8080 -e HOST="" go-webapp-golangdk:{{.GIT_TAG}}
    silent: false
